name: hw-json-lens
version: '0.0.0.1'
synopsis: Lens for hw-json
description: Please see README.md
category: Data
author: Alexey Raga, John Ky
maintainer: alexey.raga@gmail.com, newhoggy@gmail.com
copyright: 2016 Alexey Raga, 2018 John Ky
license: MIT
github: haskell-works/hw-json-lens
homepage: http://github.com/haskell-works/hw-json-lens#readme

extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base                  >= 4          && < 5
- bytestring            >= 0.10       && < 0.11
- hw-json               >= 0.8.1      && < 0.9
- lens                  >= 4          && < 5

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.Json.Lens
  - HaskellWorks.Data.ListMap
  dependencies:
  - containers          >= 0.5        && < 0.6
  - scientific          >= 0.3        && < 0.4
  - word8               >= 0.1        && < 0.2

  tests:
  hw-json-lens-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec                 >= 2.5        && < 2.6
    - hw-bits               >= 0.7        && < 0.8
    - hw-balancedparens     >= 0.2        && < 0.3
    - hw-json-lens
    - hw-prim               >= 0.6.2.0    && < 0.7
    - vector                >= 0.12       && < 0.13

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion             >= 1.4        && < 1.5
    - hw-json-lens
