resolver: lts-12.26

packages:
- '.'

flags: {}

extra-package-dbs: []

extra-deps:
  - hw-json-1.0.0.1
  - hw-json-simd-0.1.0.1
  - hw-mquery-0.2.0.1
  - hw-parser-0.1.0.0
  - hw-rankselect-0.12.0.4
  - hw-simd-0.1.1.3
  - lens-4.17
